rigid_bodies:
  '1':
    pose: robot/pose
    pose2d: robot/pose2d
    child_frame_id: robot
    parent_frame_id: world
    
  '2':
    pose: table_origin/pose
    pose2d: table_origin/pose2d
    child_frame_id: table_origin
    parent_frame_id: world
    
  '3':
    pose: positioner_origin/pose
    pose2d: positioner_origin/pose2d
    child_frame_id: positioner_origin
    parent_frame_id: world

  '4':
    pose: actor/pose
    pose2d: actor/pose2d
    child_frame_id: actor
    parent_frame_id: world

