rigid_bodies:
  '1':
    pose: robot_markerset/pose
    pose2d: robot_markerset/pose2d
    child_frame_id: robot_markerset
    parent_frame_id: testbed_origin
    
  '2':
    pose: table_origin/pose
    pose2d: table_origin/pose2d
    child_frame_id: table_origin
    parent_frame_id: testbed_origin
    
  '3':
    pose: positioner_origin/pose
    pose2d: positioner_origin/pose2d
    child_frame_id: positioner_origin
    parent_frame_id: testbed_origin

  '4':
    pose: robot_markerset/pose
    pose2d: robot_markerset/pose2d
    child_frame_id: robot_markerset
    parent_frame_id: testbed_origin

